LOGIN_REQUIRED = 'You need to log in to acces this page'
USER_CREATED = 'User created succesfully.'
LOGIN = 'Successfully authenticated user!'
LOGOUT = 'You have been successfully logged out.'
ERROR_USER_PASSWORD = 'Incorrect username or password.'
TASK_CREATED = 'Task created.'
TASK_UPDATED = 'Task updated.'
TASK_DELETED = 'Task deleted.'
